import { Locale } from 'adminjs';
import { fi, is } from 'zod/v4/locales';

export const es: Locale = {
  language: 'es',
  translations: {
    labels: {
      navigation: 'Navegación',
      loginWelcome: 'Bienvenido al panel de administración',
      Users: 'Usuarios',
      Roles: 'Roles',
      PaymentData: 'Datos de pago',
      PaymentMethods: 'Métodos de pago',
      Events: 'Eventos',
      EventMusics: 'Solicitudes musicales',
      Mentions: 'Menciones',
      ListEventMusics: 'Listas',
      EventPackages: 'Paquetes',
      Music: 'Canciones',
      CompanyData: 'Datos de empresa',
      Subscriptions: 'Suscripciones',
      Plans: 'Planes',
    },
    messages: {
      loginWelcome: 'Inicia sesión para acceder al panel',
      successfullyBulkDeleted: 'Registros eliminados correctamente',
      successfullyDeleted: 'Registro eliminado correctamente',
      successfullyUpdated: 'Registro actualizado correctamente',
      successfullyCreated: 'Registro creado correctamente',
      noRecordsInResource: 'No hay registros en este recurso',
      confirmDelete: '¿Estás seguro de que deseas eliminar este registro?',
    },
    buttons: {
      save: 'Guardar',
      addNewItem: 'Agregar nuevo',
      filter: 'Filtrar',
      applyChanges: 'Aplicar cambios',
      resetFilter: 'Restablecer filtros',
      confirmRemovalMany: 'Confirmar eliminación de múltiples',
      confirmRemoval: 'Confirmar eliminación',
      logout: 'Cerrar sesión',
      login: 'Iniciar sesión',
      seeTheDocumentation: 'Ver documentación',
      createFirstRecord: 'Crear primer registro',
    },
    actions: {
      new: 'Crear registro',
      list: 'Listado',
      edit: 'Editar',
      show: 'Ver',
      delete: 'Eliminar',
    },
    properties: {
      username: 'nombre de usuario',
      password: 'Contraseña',
      email: 'Correo',
      first_name: 'Nombre',
      last_name: 'Apellido',
      role: 'Rol',
      id: 'ID',
      name: 'Nombre',
      description: 'Descripción',
      is_active: 'Activo',
      is_paid: 'Pagado',
      is_superuser: 'Superusuario',
      subscription_status: 'Estado de suscripción',
      is_demo: 'Usó demo',
      subscription_end: 'Fin de suscripción',
      roleId: 'Rol',
      createdAt: 'Creado el',
      updatedAt: 'Actualizado el',
    },
  },
};
